src/BDP/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from rest_framework_jwt.views import (
    obtain_jwt_token,
    verify_jwt_token,
    refresh_jwt_token,
)
from bloodbank.views import RegisterView, LoginView
from bloodbank.urls import BloodCatalogListView

urlpatterns = [
    url(r'^$', BloodCatalogListView.as_view(), name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^bloodcatalog/', include("bloodbank.urls", namespace="bloodcatalog")),
    url(r'^api/', include("bloodbank.api.urls", namespace="bloodcatalog-api")),
    url(r'^token/obtain/', obtain_jwt_token, name="token-obtain"),
    url(r'^token/verify/', verify_jwt_token, name="token-verify"),
    url(r'^token/refresh/', refresh_jwt_token, name="token-refresh"),
]

src/bloodbank/urls.py
from django.conf.urls import url
from bloodbank.views import (
    BloodCatalogListView,
    BloodCatalogDetailView,
    BloodCatalogCreateView,
    BloodCatalogUpdateView,
)

urlpatterns = [
    url(r'^$', BloodCatalogListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', BloodCatalogDetailView.as_view(), name="detail"),
    url(r'^create/$', BloodCatalogCreateView.as_view(), name="create"),
    url(r'^update/(?P<pk>\d+)/$', BloodCatalogUpdateView.as_view(), name="update"),
]

src/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class="container">
    <h1>Blood Portal</h1>
    <p>Viewing as <a href="#">{{user}}</a></p>
    <a href='{% url "home" %}'>Home</a>
    <a href='{% url "register" %}'>Register</a>
    <a href='{% url "login" %}'>Log In</a>
    <a href='{% url "bloodcatalog:list" %}'>Blood Catalog</a>
    <a href='{% url "logout" %}'>Log Out</a>
</div>